CREATE SEQUENCE PRODUCT_ID_SEQUENCE START WITH 1;

CREATE TABLE PRODUCT
(
    TENANT_ID    BIGINT,
    PRODUCT_ID   BIGINT,
    PRODUCT_NAME VARCHAR,

    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (TENANT_ID) REFERENCES TENANT (TENANT_ID)
);
